version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "Cyb3r-Jak3"
    commit-message:
      prefix: "Action Update"
    reviewers:
      - "Cyb3r-Jak3"

  - package-ecosystem: "docker"
  # Can only list one directory and the PyPi tags are the main ones
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
        - "Cyb3r-Jak3"
    labels:
        - "dependencies"
    reviewers:
        - "Cyb3r-Jak3"