services:
  unbound_exporter:
    image: "ghcr.io/cyb3r-jak3/unbound-exporter:latest@sha256:35a217f7ccb3a48f56529bae7056eae6133fc6b4814e60533a36120cf394862d"
    command: [ "-unbound.host=unix:///var/run/socket/unbound.ctl" ]
    volumes:
      - socket:/var/run/socket:ro
    ports:
      - "9167:9167"
    depends_on:
      unbound:
        condition: service_started

  unbound:
    image: "mvance/unbound:1.22.0@sha256:76906da36d1806f3387338f15dcf8b357c51ce6897fb6450d6ce010460927e90"
    volumes:
      - socket:/var/run/socket:rw
      - ./unbound.conf:/opt/unbound/etc/unbound/unbound.conf
    ports:
      - "1053:1053/udp"
      - "1053:1053/tcp"
volumes:
  socket: